export { default as Home } from './Home';
export { default as Product } from './Product';
export { default as Profile } from './Profile';
export { default as ProductDetail } from './ProductDetail';
export { default as ProductNew } from './ProductNew';
export { default as ProductEdit } from './ProductEdit';
export { default as BrokerApproval } from './BrokerApproval';
export { default as Login } from './Login'; 
export { default as Regis } from './Regis'; 